### ISSUE TITLE
Doesn't work for imports in the same directory

### ISSUE THREAD

**Issue by nolawnchairs** [dword-design/eslint-plugin-import-alias#133]
When importing from the same directory, this rule doesn't get applied. It considers this valid:
```
import { Foo } from './foo'
```

Expectation:
```
import { Foo } from '@/path/to/foo'
```

All my valid imports have the error: `Unexpected subpath import via alias`

### Real world example:
```
Unexpected subpath import via alias '@lib/constants/a2.constants'. Use './constants/a2.constants' instead
```

Configuration in .eslintrc.js:
```
'@dword-design/import-alias/prefer-alias': [
  'error',
  {
    'alias': {
      '@lib': './src/'
    }
  }
],
```

Is there a way to get this to work with `.` and not just `..`?

**Comment by roryabraham** [comment]
I also would prefer to use this and standardize on always using aliases, maybe would be a useful config option

**Comment by beingfranklin** [comment]
👋🏽 Hello,

I'm working with a TypeScript project that doesn't use Babel and I've run into a problem with the `@dword-design/import-alias/prefer-alias` rule. Alongside converting aliased imports like `@/xyz` to `./xyz` in the same directory, it's also not correctly recognising imports from the same directory. 

Is there a configuration option or workaround available to address these issues, particularly for maintaining aliased paths and ensuring correct import recognition in projects without Babel?

Thanks in advance for any assistance or insights!
