### ISSUE TITLE
Error: Failed to load config "plugin:import-alias/recommended" to extend from.

### ISSUE THREAD

**Issue by apski** [dword-design/eslint-plugin-import-alias#74]
Hi - I'm having trouble with getting this plugin working. I followed the instructions in the README and get this error: 

```
Error: Failed to load config "plugin:import-alias/recommended" to extend from.
```
👋

**Comment by rkorzhoff** [comment]
@apski It seems working if you pass 'plugin:@dword-design/import-alias/recommended' instead
